- id: '1780626059606'
  name: Principais
  entities:
    light.cozinha:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6500
      supported_color_modes:
      - color_temp
      - hs
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 6500
      hs_color:
      - 49.231
      - 1.944
      rgb_color:
      - 255
      - 254
      - 250
      xy_color:
      - 0.326
      - 0.333
      friendly_name: Cozinha
      supported_features: 0
      state: 'on'
    light.meio:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6500
      supported_color_modes:
      - color_temp
      - hs
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 3521
      hs_color:
      - 27.152
      - 44.32
      rgb_color:
      - 255
      - 193
      - 142
      xy_color:
      - 0.452
      - 0.373
      friendly_name: Meio
      supported_features: 0
      state: 'on'
  metadata: {}
  icon: mdi:floor-lamp-torchiere-variant-outline
